title: Oomph Grey Matter
description: A wireframe system for quick HTML/SASS prototypes
  
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: '/grey-matter/'
port: 4000
url: //jhogue.dev.oomphcloud.com
twitter_handle: oomphinc

# Define some defaults
defaults:
  -
    values:
      layout: "page"
      author: "Oomph, Inc."


# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'node_modules', 'Procfile', 'feed.xml']

#Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

sass:
  sass_dir: _sass